<?php if($poNumber = $block->getOrderPoNumber()):?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Order Purchase Number') ?></span>
        </div>
        <div class="admin__page-section-content">
            <?php echo $block->escapeHtml($poNumber);?>
        </div>
    </section>
<?php endif; ?>
